{% set name = "mpldatacursor" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mpldatacursor-{{ version }}.tar.gz
  sha256: 738afeb4c71e1586796b30eddedfc4790619062f745874cdf1e45336a32df0bf

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - matplotlib-base >=0.9
    - numpy >=1.1

test:
  imports:
    - mpldatacursor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/joferkington/mpldatacursor/
  summary: Interactive data cursors for Matplotlib
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
